export const COUNTER_INCREMENT = 'COUNTER_INCREMENT';
export const COUNTER_DECREMENT = 'COUNTER_DECREMENT';
export const ADD_TO_COUNTER = 'ADD_TO_COUNTER';
export const SUBSTRACT_FROM_COUNTER = 'SUBSTRACT_FROM_COUNTER';
export const MULTIPLY_TO_COUNTER = 'MULTIPLY_TO_COUNTER';
export const DIVIDE_COUNTER = 'DIVIDE_COUNTER';
